### ISSUE TITLE
量化投资是什么？

### ISSUE THREAD

**Issue by Peter-YAN** [zhangchuheng123/test_jupyterpost#1]
谢谢分享，贡献，这两天在拜读iQuant。
在第二讲中，
量化投资是什么？---再讲一个量化模型：套利与套利定价模型(APT）
当然最重要的一点就是盈利为正，即

> ∑Ni=10，结合前两条，有∑Ni=1wiαi=0 

这里符号用错了吧？ **=**  --->   **>**  

发现一个错别字，历史限价委托**_薄_**数据， 应该改为 历史限价委托*_*簿**_数据， chapter_3.html

**Comment by zhangchuheng123** [comment]
感谢指正，本项目已经移到 https://zhuanlan.zhihu.com/p/55993709 并已经改正。
